name: getting_started
description: Getting Started with genezio
version: 1.0.0
repository: https://github.com/genez-io/genezio-examples

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  mongo_dart: ^0.9.1
  json_annotation: ^4.8.0

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
